### ISSUE TITLE
One unsafe block = tons of fun memory corruptions! ✨🔥

### ISSUE THREAD

**Issue by fasterthanlime** [EmbarkStudios/tame-oauth#20]
**Describe the bug**

By the powers vested in me by ASAN:

```
==17645==ERROR: AddressSanitizer: attempting double-free on 0x611000138fc0 in thread T5 (tokio-runtime-w)
```

**To Reproduce**

1. Use tame-gcs in a lot of parallel tasks on the tokio threaded runtime
2. Notice fun glibc errors (like `corrupted size vs. prev_size`)
3. Build with `-Zsanitizer=address`
4. Notice https://github.com/EmbarkStudios/tame-oauth/blob/d1762592ff29f74d58cb69e016dc1ac012863fbe/src/gcp/mod.rs#L244 in the stack trace
5. Ctrl-f the source for `unsafe`, find this https://github.com/EmbarkStudios/tame-oauth/blob/d1762592ff29f74d58cb69e016dc1ac012863fbe/src/gcp/mod.rs#L78-L98

**Expected behavior**

No memory corruption

**Screenshots**

![image](https://user-images.githubusercontent.com/7998310/95632283-987a1d80-0a85-11eb-8a06-0852a3ccaaed.png)

**Device:**
 - OS: ArchLinux on WSL2, but I can run any kind of penguin on any subsystem if needed
 - Browser: thankfully, not involved
 - Version: tame-oauth 0.4.3, same code is still in master

**Additional context**

There's no rush there, I'm forking it to use a `Mutex` or an `RwLock` instead - but you might want to look into it still, especially if you've been getting some unexplained memory corruption.

**Comment by Jake-Shadle** [comment]
Oops, thanks for the report!

**Comment by fasterthanlime** [comment]
Thanks for the quick fix! 🙌
