### ISSUE TITLE
WASM Support

### ISSUE THREAD

**Issue by fosskers** [EmbarkStudios/tame-oauth#36]
**Describe the bug**

Some colleagues and I are attempting OAuth in the browser through WASM. In general this is to communicate with certain Google APIs. Many (all?) of the existing crates for OAuth make assumptions about how you want the request to be made, and so come prepackaged with the `hyper` stack, etc. I was really happy to discover `tame-oauth`, because in theory it would let me use the browser's native Fetch capabilities (which is the primary way to make REST calls in [Seed][seed]).

[After much debugging][debugging] a mysterious linking error which many people have been hitting recently, I came to diving into the code of `tame-oauth` directly. I initially thought the issue had to do with `chrono`, but now I believe it to be due to the use of `ring`, as it seems to require system randomness. Instead of failing to compile under WASM, the linker silently throws its hands up and produces code that can't be loaded (see the linked issue and its sister issues).

Would you be open to the idea of switching off of `ring` in an attempt to achieve full WASM support for this crate? A full switch might not be necessary: we might be able to swap in a wasm-compatable crate via feature flags. For instance: https://lib.rs/crates/getrandom

It's also possible that `ring` isn't the only culprit here. As the authors of this crate, if you have any thoughts here, please let me know. 

**To Reproduce**

I've [produced a repository][repo] that demonstrates the issue fully. If you follow the instructions in its README you should arrive upon the same results.

**Expected behavior**

`tame-oauth` can be used in WASM to obtain GCP tokens.

[seed]: https://github.com/seed-rs/seed
[debugging]: https://github.com/rustwasm/wasm-bindgen/issues/2570
[repo]: https://github.com/fosskers/env-bug-test

**Comment by fosskers** [comment]
Some more context: I'm able to depend on `tame-oauth` and its types without issue. If, however, I have code that calls `ServiceAccountAccess::get_token`, the linker issue appears. It was diving through the call stack of `get_token` that I noticed the usage of `ring`, etc.

Why I thought there might be another culprit at play here is that even with the following diff applied, I still get the issue:

``` diff
diff --git a/src/gcp/jwt.rs b/src/gcp/jwt.rs
index f21fa09..943bd51 100644
--- a/src/gcp/jwt.rs
+++ b/src/gcp/jwt.rs
@@ -147,10 +147,10 @@ fn sign_rsa(
 
     let key_pair = std::sync::Arc::new(key_pair);
     let mut signature = vec![0; key_pair.public_modulus_len()];
-    let rng = ring::rand::SystemRandom::new();
-    key_pair
-        .sign(alg, &rng, signing_input.as_bytes(), &mut signature)
-        .map_err(Error::InvalidRsaKey)?;
+    // let rng = ring::rand::SystemRandom::new();
+    // key_pair
+    //     .sign(alg, &rng, signing_input.as_bytes(), &mut signature)
+    //     .map_err(Error::InvalidRsaKey)?;
 
     Ok(base64::encode_config(&signature, base64::URL_SAFE_NO_PAD))
 }
diff --git a/src/gcp/mod.rs b/src/gcp/mod.rs
index 9eb8b69..6294cca 100644
--- a/src/gcp/mod.rs
+++ b/src/gcp/mod.rs
@@ -139,7 +139,9 @@ impl ServiceAccountAccess {
             }
         };
 
-        let issued = chrono::Utc::now().timestamp();
+        let issued = 1622762400;
+        // let issued: i64 = chrono::Utc::now().timestamp();
         let expiry = issued + 3600 - 5; // Give us some wiggle room near the hour mark
 
         let claims = jwt::Claims {
```

**Comment by Jake-Shadle** [comment]
Thanks for the extensive repro case, I've made changes in #37 that should address your usecase. I'll wait until you have a chance to look at the PR in case you have any suggestions, as while we heavily use WASM in our own projects we don't target the web, nor use this particular crate from wasm itself, so I don't want to use that that PR fully addresses your situation.
